# Generated by Django 4.2.23 on 2025-07-18 00:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Adicional')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço (R$)')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível?')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_entrega_padrao', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='taxa da Entrega Padrão (R$)')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do ítem')),
                ('tipo_item', models.CharField(choices=[('ARROZ', 'Arroz'), ('FEIJAO', 'Feijao'), ('GUARNICAO', 'Guarnicao'), ('PROTEINA', 'proteina')], max_length=10, verbose_name='Tipo do Item')),
            ],
        ),
        migrations.CreateModel(
            name='TamanhoQuentinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Tamanho')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço Base (R$)')),
                ('limite_proteinas', models.PositiveIntegerField(default=1, verbose_name='Limite de Proteínas')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone (Whatsapp)')),
                ('endereco_rua', models.CharField(max_length=200, verbose_name='Rua/Avenida')),
                ('endereco_numero', models.CharField(max_length=20, verbose_name='Número')),
                ('endereco_bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('endereco_referencia', models.CharField(blank=True, max_length=200, verbose_name='Ponto de referência')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taxa de Entrega (R$)')),
                ('preco_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Preço total (R$)')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Pedido')),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('EM_PREPARO', 'Em preparo'), ('SAIU_PARA_ENTREGA', 'Saiu para Entrega'), ('CONCLUIDO', 'Concluido')], default='RECEBIDO', max_length=20, verbose_name='Status do Pedido')),
                ('adicionais_escolhidos', models.ManyToManyField(blank=True, to='pedidos.adicional', verbose_name='Adicionais')),
                ('itens_escolhidos', models.ManyToManyField(to='pedidos.itemcardapio', verbose_name='Itens Escolhidos')),
                ('tamanho_quentinha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.tamanhoquentinha', verbose_name='Tamanho da Quentinha')),
            ],
        ),
    ]
