# Generated by Django 4.2.23 on 2025-07-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CREDITO', 'Credito'), ('DEBITO', 'Debito')], default='PIX', max_length=20, verbose_name='Método de Pagamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_troco_para',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Troco para (R$)'),
        ),
    ]
