# Generated by Django 4.2.23 on 2025-07-20 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_metodo_pagamento_pedido_valor_troco_para'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tamanho_quentinha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.tamanhoquentinha', verbose_name='Tamanho da Quentinha'),
        ),
    ]
